from setuptools import find_packages, setup
setup(
name= ’pythonlib’,
packages= find_packages(include=[‘pythonlib’]),
version= ’0.1.0',
description= ’Python library’,
author= ’Me’,
license= ’MIT’,
install_requires=[],
setup_requires=[‘’],
tests_require=[‘pytest==4.4.1’],
setup_requires=[‘django==1.11.0’],
setup_requires=[‘dj-database-url==0.2.1’],
setup_requires=[‘djangorestframework==2.3.1’],
setup_requires=[‘py==1.8.1’],
setup_requires=[‘pip==19.0.3’],
setup_requires=[‘setuptools==40.8.0’],
setup_requires=[‘parse==1.14.0’],
setup_requires=[‘pluggy==0.13.1’],
setup_requires=[‘requests==1.2.0’],
setup_requires=[‘django-model-utils==1.1.0’],
setup_requires=[‘bpython==0.12’],
setup_requires=[‘tensorflow==2.4.0’],
setup_requires=[‘django-braces==0.2.1’],
setup_requires=[‘django-oauth2-provider==0.2.4’],
setup_requires=[‘attrs==19.3.0’]
test_suite=’tests’,
)
